config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "teams#index"
  resources :teams do
    resources :members
  end
  resources :projects do
    
  end
end


#projects/1/members

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  validates_presence_of :first_name, :last_name
  belongs_to :team
  has_many :project_members, dependent: :destroy
  has_many :projects, through: :project_members

  def permitted_attributes
    [:first_name, :last_name, :city, :state, :country, :team_id]
  end

  def name
    "#{first_name} #{last_name}"
  end
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, presence: true
  has_many :project_members, dependent: :destroy
  has_many :members, through: :project_members

  def permitted_attributes
    [:name, member_ids: []]
  end
end

app/models/project_member.rb
class ProjectMember < ApplicationRecord
  belongs_to :project
  belongs_to :member
end

app/models/team.rb
class Team < ApplicationRecord
  validates :name, presence: true
  has_many :members, dependent: :destroy

  def permitted_attributes
    [:name]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/resourceable.rb
module Resourceable
  extend ActiveSupport::Concern

  included do
    before_action :find_resource, only: [:edit, :update, :destroy, :show]
  end

  def index
    @resources = klass.all
    respond_with(@resources)
  end

  def show
    respond_with(@resource)
  end

  def edit
    respond_with(@resource)
  end

  def update
    if @resource.update(resource_params)
      respond_with(@resource, status: :ok)
    else
      render json: @resource.errors, status: :unprocessable_entity
    end
  end

  def new
    @resource = klass.new
    respond_with(@resource)
  end

  def create
    @resource = klass.new(resource_params)
    if @resource.save
      respond_with(@resource, status: :created)
    else
      render json: @resource.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @resource.destroy
    redirect_to [controller_name.to_sym], notice: "Deleted"
  end

  private

  def find_resource
    @resource = klass.find(params[:id])
  end

  def klass
    controller_name.singularize.camelize.constantize
  end

  def resource_params
    params.require(resource_name).permit(*klass.new.attributes.keys)
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_team
  include Resourceable

  def destroy
    @resource.destroy
    redirect_to team_members_path(@team), notice: "Deleted"
  end

  private
  def set_team
    @team = Team.find(params[:team_id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include Resourceable


  def index
    @resources = Project.all
  end

  def show
    @project = Project.find(params[:id])
    @members = @project.members
  end

  def members
    @project = Project.find(params[:id])
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  include Resourceable

  def members
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def edit_link(resource, name = "Edit")
    link_to name, [:edit, resource], class: "edit-link"
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-dark navbar-expand-sm bg-dark fixed-top">
  <div class="container">
    <a href="/" class="navbar-brand">
      <i class="fas fa-blog"></i> &nbsp; Home
    </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div id="navbarCollapse" class="collapse navbar-collapse">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a href="/projects" class="nav-link active">
            Projects
          </a>
        </li>
        <li class="nav-item">
          <a href="/teams" class="nav-link active">
            Teams
          </a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header style='z-index:100;'>
      <%= render 'layouts/navbar' %>
    </header>
    <section class='pt-5'>
      <div class='container mt-5'>
        <% unless notice.nil? %>
          <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <%= notice %>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        <% end %>
        <% unless alert.nil? %>
          <div class="alert alert-warning alert-dismissible fade show mt-3" role="alert">
            <%= alert %>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        <% end %>
        <%= yield %>
      </div>
    </section>
  </body>
</html>

app/views/members/_form.html.erb
<div class="">
  <%= simple_form_for [@team, @resource] do |f| %>
    <%= f.error_notification%>
    <div class="row">
      <div class="col-md-4">
        <%= f.input :first_name, input_html: {class: "form-control"} %>
      </div>
      <div class="col-md-4">
        <%= f.input :last_name, input_html: {class: "form-control"} %>
      </div>
       <div class="col-md-4">
        <%= f.input :city, input_html: {class: "form-control"} %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4">
        <%= f.input :state, input_html: {class: "form-control"} %>
      </div>
      <div class="col-md-4">
        <%= f.input :country, as: :string, input_html: {class: "form-control"} %>
      </div>
       <div class="col-md-4">
        <%= f.association :team, collection: Team.all, input_html: {class: "form-control"} %>
      </div>
    </div>
    <%= render "shared/submit_button", f: f %>
  <% end %>
</div>

app/views/members/_list.html.erb
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>City</th>
      <th>State</th>
      <th>Country</th>
      <th>Team</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @resources.each do |resource| %>
      <tr>
        <td><%= resource.first_name %> </td>
        <td><%= resource.last_name %> </td>
        <td><%= resource.city %> </td>
        <td><%= resource.state %> </td>
        <td><%= resource.country %> </td>
        <td><%= link_to(resource.team.name, team_members_path(@team)) %> </td>
        <td ><%= link_to('Edit', edit_team_member_path(@team, resource)) %></td>
        <td ><%= render("shared/delete_button", name: "Delete", path: team_member_path(@team, resource)) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/members/_member.html.erb
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>City</th>
      <th>State</th>
      <th>Country</th>
      <th>Team</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= member.first_name %> </td>
      <td><%= member.last_name %> </td>
      <td><%= member.city %> </td>
      <td><%= member.state %> </td>
      <td><%= member.country %> </td>
      <td><%= member.team.name %> </td>
    </tr>
  </tbody>
</table>

app/views/members/edit.html.erb
<%= render 'form' %>

app/views/members/index.html.erb
<%= render "shared/create_button", name: "Members", path: new_team_member_path(@team.id) %>
<%= render 'list' %>

app/views/members/new.html.erb
<%= render 'form' %>

app/views/members/show.html.erb
<%= render "member", member: @resource %>

app/views/projects/_form.html.erb
<div class="">
  <%= simple_form_for @resource do |f| %>
    <%= f.error_notification%>
    <div class="row">
      <div class="col-md-6">
        <%= f.input :name, input_html: {class: "form-control"} %>
      </div>

      <div class="col-md-6">
        <%= f.association :members, collection: Member.all.map{|member| [member.name, member.id]}, input_html: {class: "form-control", multiple: true} %>
      </div>

    </div>
    <%= render "shared/submit_button", f: f %>
  <% end %>
</div>

app/views/projects/_list.html.erb
<div class="container table-responsive py-5">
  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th scope='col'>Name</th>
        <th scope='col'></th>
      </tr>
    </thead>
    <tbody>
      <% @resources.each do |resource| %>
        <tr>
          <td><%= link_to(resource.name, project_path(resource)) %> </td>
          <td><%= edit_link(resource) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/projects/edit.html.erb
<%= render 'form' %>

app/views/projects/index.html.erb
<%= render "shared/create_button", name: "Project", path: new_project_path %>
<%= render 'list' %>

app/views/projects/new.html.erb
<%= render 'form' %>

app/views/projects/show.html.erb
<%= render "shared/edit_button", name: "Edit", path: edit_project_path(@resource) %>
<%= render("shared/delete_button", name: "Delete", path: project_path(@resource)) %>

<p> Project: <b><%= @resource.name %></b></p>
<%= render "shared/members", members: @resource.members%>

app/views/shared/_create_button.html.erb
<%=link_to path , class: "" do %>
  <i class=""></i>
  <span>Create <%= name %></span>
<% end %>

app/views/shared/_delete_button.html.erb
<%= link_to name, path, class: '', method: :delete, data: {confirm: "Are you sure?"} %>

app/views/shared/_edit_button.html.erb
<%= link_to name, path, class: '' %>

app/views/shared/_errors.html.erb
<% if resource.errors.present? %>
<div class="alert alert-danger">Please review the problems below:
  <ul>
    <% resource.errors.full_messages.each do |error| %>
    <li><%= error %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_members.html.erb
<div class="container table-responsive py-5">
  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>City</th>
        <th>State</th>
        <th>Country</th>
        <th>Team</th>
      </tr>
    </thead>
    <tbody>
      <% members.each do |member| %>
        <tr>
          <td><%= member.first_name %> </td>
          <td><%= member.last_name %> </td>
          <td><%= member.city %> </td>
          <td><%= member.state %> </td>
          <td><%= member.country %> </td>
          <td><%= member.team.name %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/shared/_submit_button.html.erb
<%= f.button :submit, class: "", data: {disable_with: "Saving..."} %>